version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/github/main/repositories/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
